spring:
  # redis 配置
  redis:
    #数据库索引
    database: 2
    host: localhost
    port: 6379
    password:

  jackson:
    generator:
      write_numbers_as_strings: true

file:
  temppath: temp

fengtoos:
  default:
    avaterUrl: http://localhost:7777/images/favicon.ico
    dateFmt: yyyy-MM-dd HH:mm:ss
  ignore:
    urls:
      - /oauth/
      - /file/image
      - /auth/principal
      - /wechat
      - /mail
      - /auth/menu
      - /collect
      - /comment
      - /consignee
      - /goods
      - /order
      - /recommend
      - /sort
      - /trolley
      - /user

mybatis-plus:
  mapperLocations: classpath*:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.fengtoos.ppgraduate.auth.entity,com.pp.ppgraduate.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

